use_frameworks!

target 'ProximiioMapbox_Example' do
  platform :ios, '12.0'
  pod 'ProximiioMapbox', :path => '../'
  pod 'Proximiio'
  pod 'SnapKit'
  pod 'Kingfisher'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '5.21'
        end
    end
end
