source 'https://github.com/proximiio/proximiio-specs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '13.0'

use_frameworks!
inhibit_all_warnings!

target 'ProximiioMapbox_Example' do
  pod 'ProximiioMapbox', :path => '../'
  pod 'Proximiio'
  pod 'SnapKit'
  pod 'Kingfisher'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
          config.build_settings['ENABLE_BITCODE'] = 'NO'
          config.build_settings['CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER'] = 'NO'
          config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
          config.build_settings.delete 'ARCHS'
        end
    end
end
